source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rake'
gem 'bundler'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'pry'
gem 'pry-byebug'
gem 'colored'
gem 'http'
gem 'solargraph'
gem 'rails'