Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Max: 120
Lint/UnusedMethodArgument:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Security/Open:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - '**/Rakefile'
    - '**/spec/**/*'
    - '**/db/schema.rb'
