BOOKS_100 = [
  "97 Things Every Programmer Should Know: Collective Wisdom from the Experts",
  "A Smarter Way to Learn",
  "A Tour of C++",
  "Accelerate: Building and Scaling High-Performing Technology Organizations",
  "Advanced Ruby",
  "Algorithms Unlocked",
  "Algorithms to Live By: The Computer Science of Human Decisions",
  "An Introduction to Statistical Learning: With Applications in R",
  "Automate This: How Algorithms Came to Rule Our World",
  "Automate the Boring Stuff with Python: Practical Programming for Total Beginners",
  "Big Data",
  "Big Data: A Revolution That Will Transform How We Live, Work, and Think",
  "Big Data: Principles and best practices of scalable realtime data systems",
  "Building Microservices: Designing Fine-Grained Systems",
  "Component-Based Applications",
  "Computer Science Distilled",
  "Computer Science Distilled: Learn the Art of Solving Computational Problems",
  "Continuous Delivery: Reliable Software Releases Through Build, Test, and Deployment Automation",
  "Cookbook for Security Engineers",
  "Cryptography Engineering: Design Principles and Practical Applications",
  "Data Science from Scratch: First Principles with Python",
  "Data Structures and Algorithms",
  "Data Structures and Algorithms Made Easy",
  "Data and Goliath: The Hidden Battles to Collect Your Data and Control Your World",
  "Deep Learning, Effective Modern C++: 42 Specific Ways to Improve Your Use of C++11 and C++14",
  "Designing Data-Intensive Applications",
  "Doing Data Science",
  "Domain-Specific Languages",
  "Effective Programming: More Than Writing Code",
  "Effective Python: 59 Specific Ways to Write Better Python",
  "Eloquent JavaScript",
  "Eloquent JavaScript: A Modern Introduction to Programming",
  "Essential Scrum: A Practical Guide to the Most Popular Agile Process",
  "Fluent Python: Clear, Concise, and Effective Programming",
  "From Mathematics to Generic Programming",
  "Functional Programming in Scala",
  "Game Programming Patterns",
  "Ghost in the Wires: My Adventures as the World's Most Wanted Hacker",
  "GitHub Explained",
  "Grokking Algorithms An Illustrated Guide For Programmers and Other Curious People",
  "High Performance Browser Networking",
  "How Google Tests Software",
  "How Google Works",
  "How to Create a Mind: The Secret of Human Thought Revealed",
  "Implementing Domain-Driven Design",
  "Introduction to Computation and Programming Using Python",
  "Java 8 in Action",
  "JavaScript and jQuery: Interactive Front-End Web Development",
  "Kingpin: How One Hacker Took Over the Billion-Dollar Cybercrime Underground",
  "Land of LISP: Learn to Program in LISP, One Game at a Time!",
  "Lauren Ipsum",
  "Lead the Way",
  "Learn Python The Hard Way",
  "Learn Ruby On Rails",
  "Learn You a Haskell for Great Good!",
  "Learn you some Erlang for great good!",
  "Learning Python",
  "Learning Ruby",
  "Make Your Own Neural Network",
  "Markdown Guide",
  "Mastering Bitcoin: Unlocking Digital Cryptocurrencies",
  "Metasploit: The Penetration Tester's Guide",
  "Mining of Massive Datasets",
  "Neural Networks and Deep Learning",
  "Nine Algorithms That Changed the Future: The Ingenious Ideas That Drive Today's Computers",
  "NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence",
  "Our Final Invention: Artificial Intelligence and the End of the Human Era",
  "Practical Foundations for Programming Languages",
  "Practical Object Oriented Design in Ruby",
  "Practical Vim: Edit Text at the Speed of Thought",
  "Python for Data Analysis",
  "Quantum Computing Since Democritus",
  "REST in Practice: Hypermedia and Systems Architecture",
  "Seven Concurrency Models in Seven Weeks: When Threads Unravel",
  "Seven Databases in Seven Weeks: A Guide to Modern Databases and the NoSQL Movement",
  "Seven Languages in Seven Weeks",
  "Site Reliability Engineering: How Google Runs Production Systems",
  "Steve Jobs",
  "Superintelligence: Paths, Dangers, Strategies",
  "The Architecture of Open Source Applications",
  "The Art of Computer Programming, Volumes 1-4a Boxed Set",
  "The Art of Readable Code",
  "The Clean Coder: A Code of Conduct for Professional Programmers",
  "The Design of Design: Essays from a Computer Scientist",
  "The Effective Engineer: How to Leverage Your Efforts In Software Engineering to Make a Disproportionate and Meaningful Impact",
  "The Golden Ticket: P, Np, and the Search for the Impossible",
  "The Information: A History, a Theory, a Flood",
  "The Innovators: How a Group of Hackers, Geniuses and Geeks Created the Digital Revolution",
  "The Joy of Clojure",
  "The Linux Programming Interface: A Linux and Unix System Programming Handbook",
  "The Master Algorithm: How the Quest for the Ultimate Learning Machine Will Remake Our World",
  "The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win",
  "The Principles of Object-Oriented JavaScript",
  "Think Complexity: Complexity Science and Computational Modeling",
  "Think Like a Programmer: An Introduction to Creative Problem Solving",
  "Turing's Cathedral: The Origins of the Digital Universe",
  "Understanding Computation: From Simple Machines to Impossible Programs",
  "Windows® Internals, Part 1: Covering Windows Server® 2008 R2 and Windows 7",
  "You Don't Know JS: Scope and Closures (You Don't Know JS, #2)",
  "You Don't Know JS: Up & Going"
]
