require 'rake'
require 'rake/testtask'

require 'minitest/autorun'
require 'minitest/pride'

task :default do
  describe "Exercise" do
    it "should have a blog.html file" do
      File.exists?("blog.html").must_equal true
    end
    it "should have a contact.html file" do
      File.exists?("contact.html").must_equal true
    end
  end
end