task :eslint do
  system "../../node_modules/.bin/eslint lib/*.js"
end

task :mocha do
  # Needed for Kitt
end

# note(valerieschraauwers): Replace this with a task to `open index.html` ? (same for other exercises..?)
task :webpack do
  system "../../node_modules/.bin/webpack-dev-server"
end

task default: [:eslint]
