source "https://rubygems.org"

gem "binding_of_caller"
gem "faker"
gem "pry-byebug"
gem "rack-test"
gem "rake"
gem "rspec"
gem "rubocop"
gem "sinatra"
gem "sinatra-contrib"
gem "sqlite3", '~> 1.7.3'
gem "thin"
